Write garmin specific ilinks as gpxx:rpt elements
GPSBabel/gpsbabel pull request #598
Opened 2020-06-21 19:34 UTC by lintondf

The garmin GDB module already extracts and stores autoroute interlink (intermediate lat/lon points) data.  This pull request outputs this data when the "garminextension" GPX option is specified as gpxx:RoutePointExtension elements.

Test data and test driver added.

2020-06-22 13:04 UTC, tsteven4 requested changes
I am still chewing on this, but here is what I have so far.

please prefer c++ nullptr instead of c NULL macro. see https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html.  clang-tidy can do this for you.  If you don't have clang-tidy you can do it by hand, or if you allowed maintainers to edit (which is the default) I could push the clang-tidy changes to lintondf:gpxoutputilinks.
```
 rm gpx.o
 bear make gpx.o
 make clang-tidy RUN_CLANG_TIDY_FLAGS="-header-filter=.*\\\.h -checks=-*,modernize-use-nullptr -fix"
```

2020-06-22 13:04 UTC, tsteven4 commented on gpx.cc
> +      (opt_garminext && gmsd != NULL && gmsd->ilinks != NULL)  ||
please check point_type.  One way to get ilinks with a different point type is using the transform filter, e.g. "-x transform,wpt=rte,del".  The check will prevent empty extensions elements from being written.

opt_garminext && gpxpt_route==point_type && ...

2020-06-22 13:04 UTC, tsteven4 commented on gpx.cc
> +          garmin_ilink_t* prior = NULL;
unfortunate that the gdb seems to include duplicate links.

2020-06-22 13:04 UTC, tsteven4 commented on gpx.cc
> +  garmin_fs_t* gmsd = garmin_fs_t::find(waypointp);
I am wondering about making this search conditional for efficiency in the normal case, i.e. when not writing garmin extensions, e.g.
  garmin_fs_t* gmsd = opt_garminext? garmin_fs_t::find(waypointp) : nullptr;

2020-06-22 16:06 UTC, tsteven4 commented on gpx.cc
> +  garmin_fs_t* gmsd = garmin_fs_t::find(waypointp);
Here is a way to only search for gmsd when using garmin extensions (as is done in waypt.cc).  Also checks point_type.

```
diff --git a/gpx.cc b/gpx.cc
index 915063c3..90d75613 100644
--- a/gpx.cc
+++ b/gpx.cc
@@ -1289,10 +1289,10 @@ void
 GpxFormat::gpx_write_common_extensions(const Waypoint* waypointp, const gpx_point_type point_type) const
 {
   // gpx version we are writing is >= 1.1.
-  garmin_fs_t* gmsd = garmin_fs_t::find(waypointp);
+  garmin_fs_t* gmsd = nullptr;
 
   if ((opt_humminbirdext && (WAYPT_HAS(waypointp, depth) || WAYPT_HAS(waypointp, temperature))) ||
-      (opt_garminext && gmsd != NULL && gmsd->ilinks != NULL)  ||
+      (opt_garminext && gpxpt_route==point_type && (gmsd = garmin_fs_t::find(waypointp)) && (gmsd->ilinks != nullptr))  ||
       (opt_garminext && gpxpt_waypoint==point_type && (WAYPT_HAS(waypointp, proximity) || WAYPT_HAS(waypointp, temperature) || WAYPT_HAS(waypointp, depth))) ||
       (opt_garminext && gpxpt_track==point_type && (WAYPT_HAS(waypointp, temperature) || WAYPT_HAS(waypointp, depth) || waypointp->heartrate != 0 || waypointp->cadence != 0))) {
     writer->writeStartElement(QStringLiteral("extensions"));
```

2020-06-25 14:15 UTC, lintondf commented
I believe I responded to your requested changes

2020-06-26 13:06 UTC, tsteven4 commented on gpx.cc
> +              writer->writeEndElement(); // "gpxx:RoutePointExtension"
This comment has been erroneously copied, please delete it

2020-06-26 13:09 UTC, tsteven4 commented
Has the addition of the gpxx:rpts been of any use to you?  Is there some program that can interpret these?

2020-06-27 23:50 UTC, lintondf commented
Yes, they provide detailed road shape point between the auto route waypoints.  The fields are present when you export GPX from BaseCamp.   Adding them to gpsbabel let’s me get everything I need from the GDB file.

Sent from my iPad

> On Jun 26, 2020, at 9:09 AM, tsteven4 <notifications@github.com> wrote:
> 
> ﻿
> Has the addition of the gpxx:rpts been of any use to you? Is there some program that can interpret these?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-28 20:18 UTC, tsteven4 commented
> Yes, they provide detailed road shape point between the auto route waypoints. The fields are present when you export GPX from BaseCamp. Adding them to gpsbabel let’s me get everything I need from the GDB file.

When I read the gpsbabel generated gpx file gdb-sample-v3-ilinks.gpx into BC it doesn't seem to use the gpxx:rpt elements.  But perhaps you aren't reading the gpx into BC but using it in some other fashion.

2020-06-30 16:55 UTC, tsteven4 commented
@lintondf, are you good with the current behavior of reading the gpsbabel generated gpx file into basecamp?

> When I read the gpsbabel generated gpx file gdb-sample-v3-ilinks.gpx into BC it doesn't seem to use the gpxx:rpt elements. But perhaps you aren't reading the gpx into BC but using it in some other fashion.

2020-06-30 17:07 UTC, gpsbabel commented
I find this weird, but hand my approval to Steven.

2020-06-30 23:23 UTC, lintondf commented
With the outstanding pull request code included it meets all my needs.

Sent from my iPad

> On Jun 30, 2020, at 12:55 PM, tsteven4 <notifications@github.com> wrote:
> 
> ﻿
> @lintondf, are you good with the current behavior of reading the gpsbabel generated gpx file into basecamp?
> 
> When I read the gpsbabel generated gpx file gdb-sample-v3-ilinks.gpx into BC it doesn't seem to use the gpxx:rpt elements. But perhaps you aren't reading the gpx into BC but using it in some other fashion.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-07-01 00:07 UTC, merged

2020-07-01 00:07 UTC, tsteven4 commented
thanks