Fixed altitude in interpolate filter
GPSBabel/gpsbabel pull request #68
Opened 2017-03-07 23:00 UTC by cj4567

The interpolate filter currently interpolates only longitude and latitude. Fixed it so it also handles altitude.

2017-03-08 00:52 UTC, gpsbabel commented on reference/track/tinterptrack.gpx
> +<?xml version="1.0" encoding="UTF-8"?>
No carriage returns in the repo, please.

2017-03-08 00:52 UTC, gpsbabel commented on reference/track/interptrack.gpx
> +<?xml version="1.0" encoding="UTF-8"?>
No carriage returns in the repo, please.

2017-03-08 01:03 UTC, GPSBabelDeveloper requested changes
Nice! Shows a good understanding of the problem. Thanx. If changing that to a QDateTime doesn't fall out, I'll take it after the CR's are removed.

2017-03-08 01:03 UTC, gpsbabel commented on interpolate.cc
> +            frac = (double)(timen - time1) / (double)(wpt->creation_time.toTime_t() - time1);
This probably breaks down for time < 1970 or > 2038 or something)  This problem isn't new and it's not your fault. Anyplace that a double is used to hold a time is probably slightly wrong these days. You could probably make frac a QDateTime and eliminate the toTime_t() and rely on the overloaded +/- operators to DTRT. If that doesn't fall out within a couple minutes, that's cool; I won't push back more than a bit on that.

2017-03-08 22:30 UTC, cj4567 commented on interpolate.cc
> +            frac = (double)(timen - time1) / (double)(wpt->creation_time.toTime_t() - time1);
frac is just between 0 and 1 here and does not hold the time. You're right though, toTime_t() will break before 1970 and after 2106. Replaced it with toSecsSinceEpoch().

2017-03-08 22:35 UTC, cj4567 commented on reference/track/interptrack.gpx
> +<?xml version="1.0" encoding="UTF-8"?>
Sorry, fixed it.

2017-03-08 22:40 UTC, cj4567 commented on interpolate.cc
> +            frac = (double)(timen - time1) / (double)(wpt->creation_time.toTime_t() - time1);
Never mind, that's only available in newer qt versions...

2017-03-09 03:14 UTC, GPSBabelDeveloper approved these changes
That's due diligence. Thanx for looking into it.

2017-03-09 03:14 UTC, merged